#! /bin/bash
#*******************************************************************************
# E.S.O. - ALMA project
#
# "@(#) $Id: buildEclipse,v 1.5 2012/01/09 14:39:47 tstaig Exp $"
#
# who       when        what
# --------  ----------  ----------------------------------------------
# jschwarz    02/10/2009

# Load functions
. standardUtilities
#
# Fetch operating system and release version
#
os_discovery

LOG=buildEclipse.log
exec > $LOG 2>&1

date

CURR_DIR=`pwd`

if [ "$OS" = "LINUX" ]
then 
  OSTAG=linux
elif [ "$OS" = "$CYGWIN_VER" ]
then
  OSTAG=cygwin
else
  echo "OS $OS not supported"
  exit -1
fi

echo "Installing Eclipse for $OSTAG"
echo 

ARCH=`getconf LONG_BIT`
# Deduce the zipfile suffix
if [ "$ARCH" = "32" ]
then
   echo "32-bit version of Eclipse is not supported"
   exit -1
else
   ARCH_VERSION=gtk-x86_64
fi

#
# Starting with ACS COMMON-2019JUN we only install Eclipse 4 (currently 4.11)
# under $ALMASW_ROOTDIR/$ALMASW_RELEASE/Eclipse4.
#
TOPDIR=$ALMASW_ROOTDIR/$ALMASW_RELEASE/Eclipse4
if [ -d $TOPDIR ]
then
  echo $TOPDIR directory exists already. I clean it up.
  rm -rf $TOPDIR
fi
SDKDIR=$TOPDIR/SDKandDeltaPack
mkdir $TOPDIR
mkdir $SDKDIR

VERSION=4.11
echo "unpacking the archives for Eclipse "$VERSION
SDKFILE=$CURR_DIR/../PRODUCTS/eclipse-SDK-$VERSION-linux-$ARCH_VERSION.tar.gz
cd $SDKDIR
tar zxf $SDKFILE
echo "$SDKFILE installed."
DELTAPACKFILE=$CURR_DIR/../PRODUCTS/eclipse-$VERSION-delta-pack.zip
unzip -oq $DELTAPACKFILE
echo "$DELTAPACKFILE installed."
echo "done with v.$VERSION"
echo ""


cd $CURR_DIR
echo Eclipse installation done
date
