version: "3.4"

x-args: &args
   USER_NAME: ${USER_NAME}
   GROUP_NAME: ${GROUP_NAME}
   USER_ID: ${USER_ID}
   GROUP_ID: ${GROUP_ID}

x-env: &env
   - DISPLAY=${DISPLAY}

x-volumes: &volumes
   - ${REPO_DIR}:/Repos:z
   - ${ALMA_DIR}/${CONTAINER_DIR}:/alma:z
   - ${HOME_DIR}/${CONTAINER_DIR}:/home/${USER_NAME}:z
   - /tmp/.X11-unix:/tmp/.X11-unix:z

x-acs-images: &common
   build:
      dockerfile: Dockerfile
      context: ./${IMAGE_OS}
      args:
         *args
   security_opt:
      - seccomp:unconfined
   image: acsdev-${IMAGE_OS}
   environment:
      *env
   volumes:
      *volumes
   working_dir: /home/${USER_NAME}
   networks:
    - acs-docker

services:
   centos6:
      <<: *common
   centos7:
      <<: *common
   centos8:
      <<: *common

networks:
   acs-docker:
      driver: bridge
